#!/bin/bash
# Build Minimal PX4 Debug Firmware for Console Testing
#
# This script builds a stripped-down PX4 firmware with ONLY:
#   - NuttX base system
#   - USB console
#   - Minimal NSH commands
#
# Purpose: Isolate USB console corruption issue
#
# Usage:
#   cd /home/rishi-patil/Desktop/FYP/rsp_2040
#   ./debug/build_minimal.sh

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PX4_DIR="$PROJECT_ROOT/px4-autopilot"
BUILD_TARGET="raspberrypi_pico_minimal"
OUTPUT_DIR="$PX4_DIR/build/$BUILD_TARGET"

print_header() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header "Minimal PX4 Debug Build"

# Check if PX4 directory exists
if [ ! -d "$PX4_DIR" ]; then
    print_error "PX4 directory not found: $PX4_DIR"
    print_error "Run setup.sh first"
    exit 1
fi

# Check if minimal.px4board exists
if [ ! -f "$PX4_DIR/boards/raspberrypi/pico/minimal.px4board" ]; then
    print_error "minimal.px4board not found!"
    print_error "Expected: $PX4_DIR/boards/raspberrypi/pico/minimal.px4board"
    exit 1
fi

print_info "Configuration: minimal.px4board"
print_info "Target: $BUILD_TARGET"

# Clean previous build
if [ -d "$OUTPUT_DIR" ]; then
    print_info "Cleaning previous build..."
    rm -rf "$OUTPUT_DIR"
fi

# Navigate to PX4 directory
cd "$PX4_DIR"

# Build
print_header "Building Minimal Firmware"
print_info "This may take 5-10 minutes..."
print_info ""

if make $BUILD_TARGET -j$(nproc) 2>&1 | tee "$PROJECT_ROOT/debug/build_minimal.log"; then
    print_header "Build Successful!"
    
    # Show output files
    print_info "Output directory: $OUTPUT_DIR"
    print_info ""
    print_info "Firmware files:"
    ls -lh "$OUTPUT_DIR"/*.{elf,bin,uf2} 2>/dev/null | while read line; do
        echo "  $line"
    done
    
    # Check if UF2 was generated
    if [ ! -f "$OUTPUT_DIR/${BUILD_TARGET}.uf2" ]; then
        print_warn "UF2 file not generated by build"
        print_info "Generating UF2 manually..."
        
        # Check for uf2conv.py
        UF2CONV="/tmp/uf2conv.py"
        if [ ! -f "$UF2CONV" ]; then
            print_info "Downloading uf2conv.py..."
            wget -q -O "$UF2CONV" https://raw.githubusercontent.com/microsoft/uf2/master/utils/uf2conv.py
            chmod +x "$UF2CONV"
        fi
        
        # Generate UF2
        python3 "$UF2CONV" -b 0x10000000 -f 0xe48bff56 \
            "$OUTPUT_DIR/${BUILD_TARGET}.bin" \
            -o "$OUTPUT_DIR/${BUILD_TARGET}.uf2"
        
        if [ -f "$OUTPUT_DIR/${BUILD_TARGET}.uf2" ]; then
            print_info "✓ UF2 generated: ${BUILD_TARGET}.uf2"
        else
            print_error "Failed to generate UF2"
            exit 1
        fi
    fi
    
    # Show firmware size
    print_header "Firmware Size"
    BIN_SIZE=$(stat -f%z "$OUTPUT_DIR/${BUILD_TARGET}.bin" 2>/dev/null || stat -c%s "$OUTPUT_DIR/${BUILD_TARGET}.bin")
    BIN_SIZE_KB=$((BIN_SIZE / 1024))
    FLASH_SIZE_KB=2048
    USAGE_PERCENT=$((BIN_SIZE_KB * 100 / FLASH_SIZE_KB))
    
    print_info "Binary size: ${BIN_SIZE_KB} KB / ${FLASH_SIZE_KB} KB (${USAGE_PERCENT}% used)"
    print_info ""
    
    # Flash instructions
    print_header "Flash Instructions"
    echo -e "${YELLOW}To flash minimal firmware:${NC}"
    echo -e ""
    echo -e "  1. Hold ${YELLOW}BOOTSEL${NC} button on OpenFC2040"
    echo -e "  2. Connect USB cable"
    echo -e "  3. Board appears as ${YELLOW}RPI-RP2${NC} drive"
    echo -e "  4. Copy UF2 file:"
    echo -e ""
    echo -e "     ${GREEN}cp $OUTPUT_DIR/${BUILD_TARGET}.uf2 /media/\$USER/RPI-RP2/${NC}"
    echo -e ""
    echo -e "  5. Board reboots automatically"
    echo -e "  6. Connect serial console:"
    echo -e ""
    echo -e "     ${GREEN}picocom -b 115200 /dev/ttyACM0${NC}"
    echo -e ""
    echo -e "${YELLOW}Expected result:${NC}"
    echo -e "  - If console ${GREEN}WORKS${NC}: Problem is in our sensor/driver config"
    echo -e "  - If console ${RED}FAILS${NC}: Problem is in base NuttX USB setup"
    echo -e ""
    
    # Copy to convenient location
    FIRMWARE_COPY="$PROJECT_ROOT/debug/${BUILD_TARGET}.uf2"
    cp "$OUTPUT_DIR/${BUILD_TARGET}.uf2" "$FIRMWARE_COPY"
    print_info "✓ Firmware copied to: $FIRMWARE_COPY"
    
else
    print_header "Build Failed!"
    print_error "Check build log: $PROJECT_ROOT/debug/build_minimal.log"
    exit 1
fi
