// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// probe //
// ----- //

#define probe_wrap_target 3
#define probe_wrap 10
#define probe_pio_version 1

#define probe_offset_write_cmd 0u
#define probe_offset_turnaround_cmd 0u
#define probe_offset_get_next_cmd 3u
#define probe_offset_read_cmd 8u

static const uint16_t probe_program_instructions[] = {
    0x80a0, //  0: pull   block
    0x7101, //  1: out    pins, 1         side 0 [1]
    0x1941, //  2: jmp    x--, 1          side 1 [1]
            //     .wrap_target
    0x90a0, //  3: pull   block           side 0
    0x6028, //  4: out    x, 8
    0x6081, //  5: out    pindirs, 1
    0x60a5, //  6: out    pc, 5
    0xa042, //  7: nop
    0x5901, //  8: in     pins, 1         side 1 [1]
    0x1047, //  9: jmp    x--, 7          side 0
    0x8020, // 10: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program probe_program = {
    .instructions = probe_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = probe_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config probe_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + probe_wrap_target, offset + probe_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

static inline void probe_gpio_init()
{
#if defined(PROBE_PIN_RESET)
    // Target reset pin: pull up, input to emulate open drain pin
    gpio_pull_up(PROBE_PIN_RESET);
    // gpio_init will leave the pin cleared and set as input
    gpio_init(PROBE_PIN_RESET);
#endif
    // Funcsel pins
    pio_gpio_init(pio0, PROBE_PIN_SWCLK);
    pio_gpio_init(pio0, PROBE_PIN_SWDIO);
    // Make sure SWDIO has a pullup on it. Idle state is high
    gpio_pull_up(PROBE_PIN_SWDIO);
}
// DAP interface says all pins have to be High-Z when disabled
static inline void probe_gpio_deinit()
{
#if defined(PROBE_PIN_RESET)
	gpio_deinit(PROBE_PIN_RESET);
	gpio_disable_pulls(PROBE_PIN_RESET);
#endif
	gpio_deinit(PROBE_PIN_SWCLK);
	gpio_disable_pulls(PROBE_PIN_SWCLK);
	gpio_deinit(PROBE_PIN_SWDIO);
	gpio_disable_pulls(PROBE_PIN_SWDIO);
}
static inline void probe_sm_init(pio_sm_config* sm_config) {
    // Set SWCLK as a sideset pin
    sm_config_set_sideset_pins(sm_config, PROBE_PIN_SWCLK);
    // Set SWDIO offset
    sm_config_set_out_pins(sm_config, PROBE_PIN_SWDIO, 1);
    sm_config_set_set_pins(sm_config, PROBE_PIN_SWDIO, 1);
#ifdef PROBE_IO_SWDI
    sm_config_set_in_pins(sm_config, PROBE_PIN_SWDI);
#else
    sm_config_set_in_pins(sm_config, PROBE_PIN_SWDIO);
#endif
    // Set SWD and SWDIO pins as output to start. This will be set in the sm
    pio_sm_set_consecutive_pindirs(pio0, PROBE_SM, PROBE_PIN_OFFSET, 2, true);
    // shift output right, autopull off, autopull threshold
    sm_config_set_out_shift(sm_config, true, false, 0);
    // shift input right as swd data is lsb first, autopush off
    sm_config_set_in_shift(sm_config, true, false, 0);
}

#endif

